
[TestMetadata] # these are configurations not used by the program, but may be usefull to know when post-processing the logged d
this_beacon_depth  = nan
other_beacon_depth = nan
horizontal_dist    = nan

[LoggerConfig] # these are configurations of the test done

test_name   = "MyTest"  # Test name should be the same for all beacons in the test
num_pings_per_beacon = 5
other_beacon_ids = [15] # a list of beacon ids that you'll be pinging in the test
use_advanced_usbl = true
    # while normal usbl uses the bearing and range to calculate the position of the other beacon
    # advanced usbl also uses the depth of the other beacon to calculate position
    # this depth is sent in the acoustic message payload.

[SeatracConfig] # These are configurations set to the seatrac driver

beacon_id           = 2 # valid ids are 1-15
env_salinity_ppt    = 0  # 0 ppt for fresh water and 35 ppt for salt water

transceiver_range_timeout_meters         = 1000
transceiver_response_delay_milliseconds  = 10 
#The above setting should be the same for all beacons or range information will be innacurate

position_filter_enabled                  = true
pos_filter_velocity_limit_meters_per_sec = 3
pos_filter_angle_limit_degrees           = 10
pos_filter_timeout_seconds               = 60

usbl_use_AHRS                   = true
auto_calc_pressure_offset       = true
auto_calc_velocity_of_sound     = true
automatic_mag_calibration       = false

### serial connection settings ###
serial_port = "/dev/ttyUSB0"


### TODO hardcode commented settings and remove from config 
# report_transceiver_msg_diagnostics = false
# report_transceiver_fix_msgs        = false

# transceiver_block_send_response = false
# transceiver_block_send_all      = false

# # valid frequencies are 0, 1, 2.5, 5, 10 or 25 Hz. 0 turns off automatic status reports 
# status_report_fequency_hertz           = 10
# status_include_temp_pressure_depth_vos = false
# status_include_yaw_pitch_roll          = false
# status_include_accel_mag_gyro          = false
# status_include_accel_cal_data               = false
# status_include_mag_cal_data                 = false
# status_include_uncompensated_accel_mag_gyro = false